# Generated by Django 4.2.17 on 2025-01-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="electronics",
            fields=[
                ("product", models.CharField(max_length=20)),
                ("price", models.CharField(max_length=30)),
                (
                    "customer_id",
                    models.CharField(
                        max_length=20, primary_key=True, serialize=False, unique=True
                    ),
                ),
            ],
        ),
    ]
